### ISSUE TITLE
Making a GitHub Page

### ISSUE THREAD

**Issue by Vivraan** [Godot-Languages-Support/godot-lang-support#43]
@ShalokShalom think it will help if we make one.

I've already started the process, could you look into it?

**Comment by ShalokShalom** [comment]
Idk, can you put it online first?

**Comment by Vivraan** [comment]
@ShalokShalom It's already online. Check out the Pages section if you can.
I'm assuming that it always publishes the file called `index.md`.

**Comment by ShalokShalom** [comment]
Can you share me the URL?

Cause how its supposed to work, according to the docs, would it land at an own repository

https://pages.github.com/

**Comment by Vivraan** [comment]
No, it can be the same repo.
https://vivraan.github.io/godot-lang-support/

**Comment by ShalokShalom** [comment]
I updated the branch.

**Comment by Vivraan** [comment]
Does the theme look okay?

**Comment by Croydon** [comment]
Could be closed in favor of https://github.com/Godot-Languages-Support/godot-lang-support/discussions/63
